サインアップ機能
shinonome-inc/backend-final-assignment-Miho-Miho-Hayakawa pull request #1
Opened 2022-12-17 08:03 UTC by Maco-s

<img width="686" alt="スクリーンショット 2022-12-17 17 02 13" src="https://user-images.githubusercontent.com/83572610/208232157-a32dea86-7eaa-4bda-a9b4-fd3e4e6a2127.png">

2022-12-17 09:23 UTC, gaato reviewed
全体的に良いと思います！細かいところを何点かコメントしたので修正お願いします。
あと black の設定できたらお願いします。

2022-12-18 08:30 UTC, HasegawaKota approved these changes

2022-12-19 06:02 UTC, Akinori13 requested changes
少しだけコメントしました！フォーマットはなるべく気を使って提出してもらえると読みやすくて助かります！
Viewとテストはとてもよく書けています！！

2023-01-02 07:38 UTC, Akinori13 approved these changes

2023-01-02 07:38 UTC, merged